name: Bump version

# on:
#   workflow_run:
#     workflows: [ "Lint" ]
#     branches: [ main ]
#     types:
#       - completed

on:
  push:
    branches: [ main ]

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: determine-version
      run: |
        VERSION=$(npx semantic-release --branches main --dry-run | { grep -i 'the next release version is' || test $? = 1; } | sed -E 's/.* ([[:digit:].]+)$/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      id: version
    - name: tag
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.email "ryshoooo@gmail.com"
        git config --global user.name "ryshoooo"
        git tag -a "${{ env.VERSION }}" -m "Releasing ${{ env.VERSION }}"
        git push --tags
