name: Bump version

# on:
#   workflow_run:
#     workflows: [ "Lint" ]
#     branches: [ main ]
#     types:
#       - completed

on:
  push:
    branches: [ main ]

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: determine-version
      run: |
        VERSION=$(npx semantic-release --branches main --dry-run | { grep -i 'the next release version is' || test $? = 1; } | sed -E 's/.* ([[:digit:].]+)$/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      id: version
    - name: test-version
      run: |
        echo "${{ env.VERSION }}"
