name: Bump version

on:
  workflow_run:
    workflows: [ "Lint" ]
    branches: [ main ]
    types:
      - completed

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: determine-version
      run: |
        npx semantic-release --branches master --dry-run | \
        { grep -i 'the next release version is' || test $? = 1; } | sed -E 's/.* ([[:digit:].]+)$/\1/')
